export enum NotificationType {
  FOLLOW = 'FOLLOW',
  FOLLOW_REQUEST = 'FOLLOW_REQUEST',
  POST_REACTION = 'POST_REACTION',
  COMMENT = 'COMMENT',
  COMMENT_REPLY = 'COMMENT_REPLY',
  COMMUNITY_KICK = 'COMMUNITY_KICK',
  COMMUNITY_BAN = 'COMMUNITY_BAN',
}
